### ISSUE TITLE
Correctly represent organization name in donor search

### ISSUE THREAD

**Issue by leoloe326** [lemontea606/NAMI-Dev#2]
As what you have written, the search key words will be capitalized and matched with table records. However, this operation is not compatible with organization name since it is not always in the format of Abbb, (in your case, it is PTSD). To make it uniform, I have already changed all the record in the database into downcase, however we still need to solve the problem of how to present this field correctly. There are two ways to do that:
1. Whatever the user has typed in, we will change it into downcase and save that into database.
2. Save what the user has typed in, but search with case sensitive.

Which way is better? @tonywang1990 @NYPatrician

**Comment by NYPatrician** [comment]
Save original data, and search with case insensitive.
